### ISSUE TITLE
RuntimeError: SWIG std::function invocation failed.

### ISSUE THREAD

**Issue by yratof** [paulgb/penkit#2]
Hitting an error whenever i'm not using greedy:

```
Initial cost: 1175670.59166
Cost after greedy optimization: 51105.4291514
Traceback (most recent call last):
  File "/usr/local/bin/penkit-optimize", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/penkit_optimize/cli.py", line 79, in main
    run_optimizer(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/penkit_optimize/cli.py", line 33, in run_optimizer
    vrp_solution = vrp_solver(path_graph, greedy_solution, runtime)
  File "/usr/local/lib/python2.7/site-packages/penkit_optimize/vrp_solver.py", line 58, in vrp_solver
    search_parameters = pywrapcp.RoutingModel.DefaultSearchParameters()
RuntimeError: SWIG std::function invocation failed.
```

Any ideas to why `invocation failed`?

**Comment by paulgb** [comment]
Hi @yratof, sorry for the slow reply, I was away. What OS are you using, and how did you install or-tools?

Thanks

**Comment by yratof** [comment]
macOS and via pip. Possibly attempted via brew too, but I don’t believe had any luck finding it

**Comment by paulgb** [comment]
Hmm, that should work (I'm using the same setup) -- might be a version mismatch.

What do you get if you run `pip freeze | grep ortools`?

Here's my output:

```
~/Projects/penkit/optimizer: pip freeze | grep ortools
ortools==6.7.4973
ortools-examples==6.4.4495
```

**Comment by yratof** [comment]
[yratof@eve:~]
% pip freeze | grep ortools                                                 1 ↵
ortools==6.7.4973

Looking like the same version
